require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TradeMessagesController do

  # This should return the minimal set of attributes required to create a valid
  # TradeMessage. As you add validations to TradeMessage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "content" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TradeMessagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all trade_messages as @trade_messages" do
      trade_message = TradeMessage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:trade_messages).should eq([trade_message])
    end
  end

  describe "GET show" do
    it "assigns the requested trade_message as @trade_message" do
      trade_message = TradeMessage.create! valid_attributes
      get :show, {:id => trade_message.to_param}, valid_session
      assigns(:trade_message).should eq(trade_message)
    end
  end

  describe "GET new" do
    it "assigns a new trade_message as @trade_message" do
      get :new, {}, valid_session
      assigns(:trade_message).should be_a_new(TradeMessage)
    end
  end

  describe "GET edit" do
    it "assigns the requested trade_message as @trade_message" do
      trade_message = TradeMessage.create! valid_attributes
      get :edit, {:id => trade_message.to_param}, valid_session
      assigns(:trade_message).should eq(trade_message)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TradeMessage" do
        expect {
          post :create, {:trade_message => valid_attributes}, valid_session
        }.to change(TradeMessage, :count).by(1)
      end

      it "assigns a newly created trade_message as @trade_message" do
        post :create, {:trade_message => valid_attributes}, valid_session
        assigns(:trade_message).should be_a(TradeMessage)
        assigns(:trade_message).should be_persisted
      end

      it "redirects to the created trade_message" do
        post :create, {:trade_message => valid_attributes}, valid_session
        response.should redirect_to(TradeMessage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved trade_message as @trade_message" do
        # Trigger the behavior that occurs when invalid params are submitted
        TradeMessage.any_instance.stub(:save).and_return(false)
        post :create, {:trade_message => { "content" => "invalid value" }}, valid_session
        assigns(:trade_message).should be_a_new(TradeMessage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TradeMessage.any_instance.stub(:save).and_return(false)
        post :create, {:trade_message => { "content" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested trade_message" do
        trade_message = TradeMessage.create! valid_attributes
        # Assuming there are no other trade_messages in the database, this
        # specifies that the TradeMessage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TradeMessage.any_instance.should_receive(:update).with({ "content" => "MyText" })
        put :update, {:id => trade_message.to_param, :trade_message => { "content" => "MyText" }}, valid_session
      end

      it "assigns the requested trade_message as @trade_message" do
        trade_message = TradeMessage.create! valid_attributes
        put :update, {:id => trade_message.to_param, :trade_message => valid_attributes}, valid_session
        assigns(:trade_message).should eq(trade_message)
      end

      it "redirects to the trade_message" do
        trade_message = TradeMessage.create! valid_attributes
        put :update, {:id => trade_message.to_param, :trade_message => valid_attributes}, valid_session
        response.should redirect_to(trade_message)
      end
    end

    describe "with invalid params" do
      it "assigns the trade_message as @trade_message" do
        trade_message = TradeMessage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TradeMessage.any_instance.stub(:save).and_return(false)
        put :update, {:id => trade_message.to_param, :trade_message => { "content" => "invalid value" }}, valid_session
        assigns(:trade_message).should eq(trade_message)
      end

      it "re-renders the 'edit' template" do
        trade_message = TradeMessage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TradeMessage.any_instance.stub(:save).and_return(false)
        put :update, {:id => trade_message.to_param, :trade_message => { "content" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested trade_message" do
      trade_message = TradeMessage.create! valid_attributes
      expect {
        delete :destroy, {:id => trade_message.to_param}, valid_session
      }.to change(TradeMessage, :count).by(-1)
    end

    it "redirects to the trade_messages list" do
      trade_message = TradeMessage.create! valid_attributes
      delete :destroy, {:id => trade_message.to_param}, valid_session
      response.should redirect_to(trade_messages_url)
    end
  end

end
